### ISSUE TITLE
Npm package has no bundles

### ISSUE THREAD

**Issue by Kroisse** [esinx/react-swr-infinite-scroll#1]
How to reproduce
------

```
$ npm i react-swr-infinite-scroll@1.0

added 10 packages, and audited 11 packages in 2s

found 0 vulnerabilities

$ ls node_modules/react-swr-infinite-scroll/
CHANGELOG.md  LICENSE  package.json  README.md  rollup.config.js  src  tsconfig.json

```

@semantic-release/npm이 의도대로 동작하지 않았거나, 혹은 배포 과정의 실수로 인해 패키징이 `dist/` 폴더가 아닌 저장소 루트에서 실행된 채로 올라간 것으로 보입니다. 올바른 버전의 패키지로 교체하고 현재 버전을 [deprecated로 표시][npm deprecate]하는 게 좋겠습니다.

It seems that `npm pack` was executed on the project root instead on `dist/`, caused by that @semantic-release/npm didn't work as intended or some mistake was happen in publishing. It might be a good idea to update the proper package and [mark as deprecated][npm deprecate] the current one. 

[npm deprecate]: https://docs.npmjs.com/cli/v7/commands/npm-deprecate

**Comment by esinx** [comment]
피드백 감사합니다! 배포 중 문제가 발생한듯 하네요. (@semantic-release/npm 사용이 익숙하지 않아 헤매었습니다 😅)
Thanks for letting me know! I suppose there was an issue with publishing (tbh I'm not really familiar with @semantic-release/npm 😅)
